# Generated by Django 2.2.7 on 2019-11-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0003_auto_20191129_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='text',
            field=models.TextField(max_length=500),
        ),
    ]
