# Generated by Django 2.2.7 on 2019-11-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0004_auto_20191129_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='asnana_field_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
