# Generated by Django 2.2.7 on 2019-11-29 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0005_task_asnana_field_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='asnana_field_id',
        ),
    ]
